### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-CQZE2NTZ78

### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
